encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="url_index"),
    # I can send the submitted query to any path.
    path("search", views.search, name="url_search"),
    path("create", views.create, name="url_create"),
    path("random", views.get_random, name="random"),
    path("<str:entry_title>", views.display, name="url_display"), 
    path("edit/<str:title>", views.edit, name="edit"),
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls") ),

]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from logging import PlaceHolder
from django import forms

# Create forms here

class SearchForm(forms.Form):
    """ Form Class for Search Bar """  
    q = forms.CharField(label='', widget=forms.TextInput(attrs={
      "class": "search",
      "placeholder": "Search Encyclopedia",}
      ))

class CreateEntry(forms.Form):
    """ Form class to create a new Entry"""
    title = forms.CharField(label="Entry Title", widget=forms.TextInput(attrs={
        "placeholder": "Enter Entry Title",
    }))
    body = forms.CharField(label="Body", widget=forms.Textarea(attrs={
        'class': "form-control",
        'rows': 3, 
        'cols': 10,
        "placeholder": "Enter content using Markdown",
    }))

class EditEntry(forms.Form):
    """ Form class to edit an existing Entry"""
    entry = forms.CharField(label="Entry", widget=forms.Textarea(attrs={
        'class': "form-control",
        'rows':15,
    }))

encyclopedia/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from markdown2 import Markdown
from . import util
from .forms import CreateEntry, SearchForm, EditEntry
import logging
from random import choice

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger()


def index(request):
    """ Returns the home/index page """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        'search_form': SearchForm(),
    })


def create(request):
    """    Handles create page view    """

    if request.method == "POST":
        form = CreateEntry(request.POST)
        if form.is_valid():
            title, body = form.cleaned_data['title'], form.cleaned_data['body']

            # If entry exists, Error msg and stay on form page
            if util.get_entry(title):
                messages.error(
                    request, 'Page already exists. Please edit using link below instead.')
                return render(request, 'encyclopedia/create.html', {
                    "create_form": form,
                    "title": title
                })
            else:
                util.save_entry(title, body)
                return redirect(reverse('encyclopedia:url_index'))

        else:
            messages.error(request, 'Form is not valid')
    return render(request, "encyclopedia/create.html", {
        "create_form": CreateEntry(),
        'search_form': SearchForm(),
    })


def edit(request, title):
    """ Edits the page """
    if request.method == "POST":
        form = EditEntry(request.POST)
        if form.is_valid():
            entry = form.cleaned_data['entry']
            util.save_entry(title, entry)
            return display(request, title)

    # Display edit page with Django text.
    return render(request, "encyclopedia/entry.html", {
        'entry_title': title,
        'search_form': SearchForm(),
        'edit': True,
        # If populating form, needs dict of the key to populate
        "edit_form": EditEntry({"entry": util.get_entry(title)}) 
    })


def display(request, entry_title):
    """ Displays the page for each entry if an entry.md exists"""

    markdowner = Markdown()
    if util.get_entry(entry_title):
        return render(request, "encyclopedia/entry.html", {
            "entry": markdowner.convert(util.get_entry(entry_title)),
            "entry_title": entry_title,
            'search_form': SearchForm(),
            'edit': False,
        })

    else:
        return render(request, "encyclopedia/404page.html")  # Error Page


def search(request):
    """ Searches for an exact entry  match or returns closest matches if exact entry not found
    """

    if request.method == 'GET':
        form = SearchForm(request.GET)

        # Server side validation of GET response. Else redirects to index
        if form.is_valid():
            GET_value = form.cleaned_data["q"]

            if util.get_entry(GET_value):           # If entry exists
                return display(request, GET_value)

            else:
                return render(request, "encyclopedia/index.html", {
                    'entries': util.get_close_matches(GET_value),
                    'GET_value': GET_value,
                    'search': True
                })

    return index(request)


def get_random(request):
    """ If random page is clicked, will randomly select an entry"""

    return display(request, choice(util.list_entries()))

encyclopedia/templates/encyclopedia/404page.html
{% extends "encyclopedia/layout.html" %}
{% load static %}


{% block title %}
    Entry Not Found!
{% endblock %}

{% block body %}

<img src="{% static '\media\cat_error.jpg' %}" width="400">

{% endblock %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Page to create/edit
{% endblock %}


{% block body %}
    <form action="{% url 'encyclopedia:url_create' %}" method="POST">
        {% csrf_token %}
        {{create_form}}
        <!-- <input type="submit" value="Save"> -->

        <button type="submit" class="btn btn-primary">
            Save
        </button>



    </form>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    <!-- insert link of title to help redirect-->
    <li>
        <a href="{% url 'encyclopedia:url_display' entry_title=title %}">{{title}}</a>
    </li>

    {% endfor %}
    {% endif %}
{% endblock %}
    

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title|capfirst  }}
{% endblock %}


{% block body %}
    <!-- Displays a regular entry page if it exists with edit button -->
    <!-- If editing, and edit=True, shows preopulated form with save button -->

    {% if edit is True  %}
    {{ entry_title }}
    <form action="{% url 'encyclopedia:edit' title=entry_title %}" method="POST">
        {% csrf_token %}
        {{  edit_form  }}

        <button type="submit" class="btn btn-primary">
            Save Page
        </button>
    </form>
    <!-- if edit is false -->
    {% else %}
    {{ entry|safe }}

    <!-- This adds a EDIT link for each title page.  Will redirect to /wiki/edit/{title}-->
    <!-- 'enclopedia:edit' is namespace. title is set to entry_title from views.py. this is then matched from urls.py, to /wiki/edit/{title}  -->
    <a class="btn btn-primary" href="{% url 'encyclopedia:edit' title=entry_title %}">Edit Page</a>

    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}


        {% if search is True %}
        <h2>Searching for {{GET_value}}</h2>
        {% else %}
            <h1>All Pages</h1>
        {% endif %}

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:url_display' entry_title=entry %}">{{entry}}</a></li>

        {% empty %}
            <li>No pages found.</li>

        {% endfor %}
        
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>


                <form action="{% url 'encyclopedia:url_search' %}" method="GET">
                    {{ search_form }}
                    <input type="submit" value="Search">
                </form>



                <div>
                    <a href="{% url 'encyclopedia:url_index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:url_create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/modify.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Page to create/edit
{% endblock %}


{% block body %}
    <form action="{% url 'encyclopedia:url_create' %}" method="POST">
        {% csrf_token %}
        {{create_form}}
        <input type="submit" value="Save">
    </form>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    <!-- insert link of title to help redirect-->
    <li>
        <a href="{% url 'encyclopedia:url_display' entry_title=title %}">{{title}}</a>
    </li>

    {% endfor %}
    {% endif %}
{% endblock %}
    